// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajUygulama2.Models;

namespace StajUygulama2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StajUygulama2.Models.OgrenciAdresBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres1");

                    b.Property<string>("Adres2");

                    b.Property<string>("Eposta");

                    b.Property<string>("PostaKodu");

                    b.Property<string>("Sehir");

                    b.Property<string>("Semt");

                    b.Property<string>("Statu");

                    b.Property<string>("Telefon1");

                    b.Property<string>("Telefon2");

                    b.HasKey("Id");

                    b.ToTable("OgrenciAdresBilgileri");
                });

            modelBuilder.Entity("StajUygulama2.Models.OgrenciAileBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnneBabaDurum");

                    b.Property<string>("KardesSayisi");

                    b.Property<string>("KiminleKaliyor");

                    b.HasKey("Id");

                    b.ToTable("OgrenciAileBilgileri");
                });

            modelBuilder.Entity("StajUygulama2.Models.OgrenciBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired();

                    b.Property<string>("Cinsiyet");

                    b.Property<string>("DogumTarihi");

                    b.Property<string>("DogumYeri");

                    b.Property<string>("Donem");

                    b.Property<string>("KanGrubu");

                    b.Property<int>("OgrenciAdresBilgiId");

                    b.Property<int>("OgrenciAileBilgiId");

                    b.Property<int>("OgrenciOkulBilgiId");

                    b.Property<string>("SilinmeTarihi");

                    b.Property<string>("Soyad")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OgrenciAdresBilgiId");

                    b.HasIndex("OgrenciAileBilgiId");

                    b.HasIndex("OgrenciOkulBilgiId");

                    b.ToTable("OgrenciBilgileri");
                });

            modelBuilder.Entity("StajUygulama2.Models.OgrenciOkulBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboneDurumu");

                    b.Property<string>("AyrilmaNedeni");

                    b.Property<string>("Notlar");

                    b.Property<string>("OdaNo");

                    b.Property<string>("OgrenciNo");

                    b.Property<string>("OgrenciTipi");

                    b.Property<string>("Okul");

                    b.Property<string>("OncekiOkul");

                    b.Property<string>("ServisNo");

                    b.Property<string>("Sınıf");

                    b.Property<string>("YatakNo");

                    b.HasKey("Id");

                    b.ToTable("OgrenciOkulBilgileri");
                });

            modelBuilder.Entity("StajUygulama2.Models.OgrenciBilgi", b =>
                {
                    b.HasOne("StajUygulama2.Models.OgrenciAdresBilgi", "OgrenciAdresBilgi")
                        .WithMany()
                        .HasForeignKey("OgrenciAdresBilgiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajUygulama2.Models.OgrenciAileBilgi", "OgrenciAileBilgi")
                        .WithMany()
                        .HasForeignKey("OgrenciAileBilgiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajUygulama2.Models.OgrenciOkulBilgi", "OgrenciOkulBilgi")
                        .WithMany()
                        .HasForeignKey("OgrenciOkulBilgiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
